#Requires -Version 7.0
<#
.SYNOPSIS
    配布する libmpv-2.dll の「対応ソース (Corresponding Source)」を取得・保管する。

.DESCRIPTION
    GPLv3 §6(b) は、バイナリ配布日から 3 年間、対応ソースを提供する義務を課す。
    第三者（zhongfly/mpv-winbuild および各 upstream）のリポジトリが将来消失しても
    義務を履行できるよう、ピン留めされたコミットを third_party/mpv-source-mirror/ へ
    クローンして手元に保管する。

    ピン値は CORRESPONDING-SOURCE.md / scripts/fetch-mpv-dev.ps1 と一致させること。
    対応ソースを配布物と共に頒布する場合は、このディレクトリをアーカイブして添付する。

.NOTES
    クローンは合計で数 GB になりうる。--depth 1 で各コミットのみ取得する。
    git が PATH にあること。
#>
[CmdletBinding()]
param(
    [switch]$Force
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

# ---- ピン値（CORRESPONDING-SOURCE.md と一致させる） ----
$BuildSystemRepo = 'https://github.com/zhongfly/mpv-winbuild.git'
$BuildSystemTag  = '2026-06-08-6444c05059'
$MpvRepo         = 'https://github.com/mpv-player/mpv.git'
$MpvCommit       = '6444c050592991d94cf36ecdb013dac193c24ff5'
$FfmpegRepo      = 'https://github.com/FFmpeg/FFmpeg.git'
$FfmpegCommit    = '6028720d70d0f50512c66df43f7c9e05d6797463'

$RepoRoot  = Split-Path -Parent $PSScriptRoot
$MirrorDir = Join-Path $RepoRoot 'third_party\mpv-source-mirror'

function Write-Step([string]$msg) { Write-Host "==> $msg" -ForegroundColor Cyan }

# 指定コミット/タグだけを shallow に取得する（タグが無い場合はコミット fetch）
function Clone-At([string]$url, [string]$ref, [string]$dest) {
    if ((Test-Path $dest) -and -not $Force) {
        Write-Step "既に取得済み: $dest （再取得は -Force）"
        return
    }
    if (Test-Path $dest) { Remove-Item -Recurse -Force $dest }
    New-Item -ItemType Directory -Force -Path $dest | Out-Null
    Write-Step "fetch $url @ $ref -> $dest"
    git -C $dest init -q
    git -C $dest remote add origin $url
    git -C $dest fetch -q --depth 1 origin $ref
    git -C $dest checkout -q FETCH_HEAD
    Remove-Item -Recurse -Force (Join-Path $dest '.git')   # スナップショットのみ残す
}

New-Item -ItemType Directory -Force -Path $MirrorDir | Out-Null

Clone-At $BuildSystemRepo $BuildSystemTag (Join-Path $MirrorDir 'mpv-winbuild')
Clone-At $MpvRepo         $MpvCommit      (Join-Path $MirrorDir 'mpv')
Clone-At $FfmpegRepo      $FfmpegCommit   (Join-Path $MirrorDir 'ffmpeg')

# 取得記録
$manifest = @"
# Corresponding Source mirror — generated by mirror-mpv-source.ps1
# GPLv3 §6(b) の 3 年間提供義務を履行するためのスナップショット。
date          : $(Get-Date -Format o)
mpv-winbuild  : $BuildSystemRepo @ $BuildSystemTag
mpv           : $MpvRepo @ $MpvCommit
ffmpeg        : $FfmpegRepo @ $FfmpegCommit

注: x264/x265/libass/dav1d 等の個別依存は mpv-winbuild のビルド定義
(build.sh / CMake パッケージ) が規定するコミットで取得される。完全な対応ソースが
必要な場合は mpv-winbuild のビルドを実行して各 src_packages を取得すること。
"@
Set-Content -Path (Join-Path $MirrorDir 'MIRROR-MANIFEST.txt') -Value $manifest -Encoding utf8

Write-Step "完了: $MirrorDir"
Write-Host "  これをアーカイブし、配布物の対応ソースとして保管/頒布すること。"
